/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Review = IDL.Record({
  'reviewText' : IDL.Text,
  'reviewerName' : IDL.Text,
});
export const BakeryProfile = IDL.Record({
  'whatsappUrl' : IDL.Text,
  'hours' : IDL.Text,
  'featuredReview' : Review,
  'name' : IDL.Text,
  'priceRange' : IDL.Text,
  'address' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'reviewCount' : IDL.Nat,
  'facebookUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'getProfile' : IDL.Func([], [BakeryProfile], ['query']),
  'getRelatedBusinesses' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Review = IDL.Record({
    'reviewText' : IDL.Text,
    'reviewerName' : IDL.Text,
  });
  const BakeryProfile = IDL.Record({
    'whatsappUrl' : IDL.Text,
    'hours' : IDL.Text,
    'featuredReview' : Review,
    'name' : IDL.Text,
    'priceRange' : IDL.Text,
    'address' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'reviewCount' : IDL.Nat,
    'facebookUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'getProfile' : IDL.Func([], [BakeryProfile], ['query']),
    'getRelatedBusinesses' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };